# Site Configuration
title: Lionel Kanyowa
description: DevOps Engineer & Infrastructure Specialist - Building scalable, secure, and automated solutions
url: "https://lionelkanyowa.com"

# Personal Information
author:
  name: Lionel Kanyowa
  email: lionelkanyowa@gmail.com
  linkedin: lionel-kanyowa
  github: lionelkanyowa
  location: "Michigan"

# Build Settings
markdown: kramdown
highlighter: rouge

# Plugins - Only use supported GitHub Pages plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Navigation
navigation:
  - title: About
    url: /about/
  - title: Projects
    url: /projects/
  - title: DevOps Roadmap
    url: /devops-roadmap/
  - title: Articles
    url: /articles/